function [jd] = datetime2julianday(matlab_datetime)
    %@code{true}
    % Assumes that the matlab datetime is on UTC time
    gregorian = [year(matlab_datetime),...
                 month(matlab_datetime),...
                 day(matlab_datetime),...
                 hour(matlab_datetime),...
                 minute(matlab_datetime),...
                 second(datetime)];
    jd = gregorian2julianday(gregorian);
end